Feature/gptl
NOAA-GSL/SENA-yppm pull request #32
Opened 2021-02-05 16:47 UTC by robgonzalezpita

## Proposed changes

Add support for profiling with [GPTL](https://github.com/jmrosinski/GPTL).  Closes  #6 .

This pull request adds two build options for profiling with GPTL.

The first option, ENABLE_GPTL, turns on profiling with GPTL and is enabled with the ENABLE_GPTL cmake flag:
```
cmake -DENABLE_GPTL=1 ......
```
The second option, ENABLE_AUTOPROFILING, turns on GPTL's autoprofiling feature if ENABLE_GPTL is also enabled:
```
cmake -DENABLE_GPTL=1 -DENABLE_AUTOPROFILING=1 ....
```

The CI MacOS and Ubuntu build tests have been updated to install GPTL and add a build test with `-DENABLE_GPTL=1 -DENABLE_AUTOPROFILING=1`

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (Change which fixes an issue)
- [x] New feature (Change which adds functionality)
- [ ] Enhancement to existing functionality (non-breaking change which improves existing code or documentation)
- [ ] Breaking change (fix or feature that changes results and requires updates to test baselines)
- [ ] Documentation Update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/NOAA-GSL/SENA-c_sw/blob/develop/CONTRIBUTING.md) document
- [x] I have ensured all my changes contribute to a common purpose
- [x] I have verified my change does not add debug code
- [x] I have verified my change does not add code that is commented out
- [x] I have verified unit tests pass locally with my changes
- [x] I have verified my changes adhere to style guidelines
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

For now, this is a draft PR.  Once the namelist I/O is sorted out, and CI is verified to work properly, it will be ready for review.

2021-02-05 17:40 UTC, LyndStringer reviewed
Looks good except for the tests not passing.

2021-02-05 18:01 UTC, christopherwharrop-noaa requested changes
A few style newline nitpicks.  Also, I believe you need to add the link libraries in the `test/CMakeLists.txt` file because the interpolation test will need them.

```
if ( GPTL_FOUND )
   target_link_libraries( ${PROJECT_NAME} PUBLIC GPTL::GPTL )
endif()
```

I think that is why the tests are failing

2021-02-05 18:01 UTC, christopherwharrop-noaa commented on ref/cmake/compiler_flags_Intel_Fortran.cmake
> +set( Fortran_AUTOPROFILING_FLAGS        "-finstrument-functions" )
Need a newline here.

2021-02-05 18:01 UTC, christopherwharrop-noaa commented on ref/src/yppm_driver.F90
> +end program yppm_driver
Need a newline here

2021-02-05 18:01 UTC, christopherwharrop-noaa commented on ref/cmake/FindGPTL.cmake
> +endif()
Need a newline here

2021-02-05 19:13 UTC, christopherwharrop-noaa commented on ref/test/CMakeLists.txt
> +   target_link_libraries( ${PROJECT_NAME} PUBLIC GPTL::GPTL )
I think you need to replace `${PROJECT_NAME}` with `interpolateTest` here.  Sorry I wasn't clear that the name of the target needed to be the name of the executable in question, which in this case is `interpolateTest`.

2021-02-05 21:37 UTC, christopherwharrop-noaa approved these changes
Thank you for tackling this.

2021-02-05 21:38 UTC, christopherwharrop-noaa commented
@LyndStringer & @middlecoff - The GPTL for yppm is no longer a Draft PR and is now ready for a proper review.

2021-02-13 05:34 UTC, LyndStringer approved these changes
Looks good.

2021-03-01 21:23 UTC, merged